services:
  - type: web
    name: mahjong-yaku-app
    env: ruby
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails server -b 0.0.0.0
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mahjong-yaku-db
          property: connectionString
